all:
  hosts:
    web1:
      ansible_host: 89.169.136.104
      ansible_user: mollyj
      ansible_ssh_private_key_file: ~/.ssh/yandex1cl
    web2:
      ansible_host: 158.160.80.22
      ansible_user: mollyj
      ansible_ssh_private_key_file: ~/.ssh/yandex2cl
