- name: Prepare servers for deployment
  hosts: all
  become: true

  tasks:
    - name: Install dependencies via Galaxy roles
      import_role:
        name: geerlingguy.pip
    - name: Install docker pip module
      pip:
        name: docker
        state: present

- name: Deploy Redmine application
  hosts: all
  become: true

  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/webservers/vault.yml

  tasks:
    - name: Ensure Redmine directory exists
      file:
        path: "/home/{{ ansible_user }}/redmine"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create .env file from template
      template:
        src: templates/redmine.env.j2
        dest: /home/{{ ansible_user}}/redmine/.env
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Pull redmine Docker image
      docker_image:
        name: redmine
        source: pull

    - name: Run Redmine container
      docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        ports:
          - "3000:3000"
        env_file: "/home/{{ ansible_user }}/redmine/.env"
        state: started

- name: Install and start DataDog Agent
  hosts: webservers
  become: yes
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_config:
      logs_enabled: true

- name: Configure DataDog HTTP check
  hosts: webservers
  become: yes
  tasks:
    - name: Deploy Datadog http_check config
      template:
        src: templates/http_check.yaml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
      notify: Restart Datadog Agent

  handlers:
    - name: Restart Datadog Agent
      service:
        name: datadog-agent
        state: restarted
